language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

git:
  depth: 10

node_js:
  - "0.12"
  - "node"

env:
  - CC=gcc-4.8 CXX=g++-4.8

branches:
  only:
    - master
