language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

git:
  depth: 10

node_js:
  - "0.12"
  - "node"

env:
  - CC=clang CXX=clang++ npm_config_clang=1

branches:
  only:
    - master
